// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonMasterAPI.Infrastructure.Data;

#nullable disable

namespace PokemonMasterAPI.Infrastructure.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20230916133618_PokemonMaster")]
    partial class PokemonMaster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("PokemonMasterAPI.Domain.Entities.Capture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CaptureDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Captures");
                });

            modelBuilder.Entity("PokemonMasterAPI.Domain.Entities.Evolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("Evolutions");
                });

            modelBuilder.Entity("PokemonMasterAPI.Domain.Entities.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("PokemonMasterAPI.Domain.Entities.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("PokemonMasterAPI.Domain.Entities.Capture", b =>
                {
                    b.HasOne("PokemonMasterAPI.Domain.Entities.Pokemon", "Pokemon")
                        .WithMany("Captures")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonMasterAPI.Domain.Entities.Trainer", "Trainer")
                        .WithMany("Captures")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("PokemonMasterAPI.Domain.Entities.Evolution", b =>
                {
                    b.HasOne("PokemonMasterAPI.Domain.Entities.Pokemon", null)
                        .WithMany("Evolutions")
                        .HasForeignKey("PokemonId");
                });

            modelBuilder.Entity("PokemonMasterAPI.Domain.Entities.Pokemon", b =>
                {
                    b.HasOne("PokemonMasterAPI.Domain.Entities.Trainer", null)
                        .WithMany("CapturedPokemons")
                        .HasForeignKey("TrainerId");
                });

            modelBuilder.Entity("PokemonMasterAPI.Domain.Entities.Pokemon", b =>
                {
                    b.Navigation("Captures");

                    b.Navigation("Evolutions");
                });

            modelBuilder.Entity("PokemonMasterAPI.Domain.Entities.Trainer", b =>
                {
                    b.Navigation("CapturedPokemons");

                    b.Navigation("Captures");
                });
#pragma warning restore 612, 618
        }
    }
}
